begin
/*manejo de exceptiones*/
BEGIN TRY

	BEGIN TRAN
   
   
    insert into Production.ProductCategory (name, ModifiedDate) values('EEEEEEEEED', GETDATE())
	insert into Production.ProductCategory (name, ModifiedDate) values('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF', GETDATE());
	
	SELECT 'TODO BIEN'
	COMMIT;

END TRY
BEGIN CATCH
 SELECT 'ERROR'
 ROLLBACK;
END CATCH
end;

